-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedElements
System.import(function (out)
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Server.Elements", function (namespace)
  namespace.class("RootElement", function (namespace)
    local HandleEvent, class, __ctor__
    __ctor__ = function (this, element)
      SlipeSharedElements.Element.__ctor__[2](this, element)
    end
    HandleEvent = function (this, eventName, element, p1, p2, p3, p4, p5, p6, p7, p8)
      local default = class.OnMiscelaniousEvent
      if default ~= nil then
        default(eventName, element, p1, p2, p3, p4, p5, p6, p7, p8)
      end
    end
    class = {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Elements.Element
        }
      end,
      HandleEvent = HandleEvent,
      __ctor__ = __ctor__
    }
    return class
  end)
end)
