-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientGui
local SystemNumerics
local WpfRendererCegui
System.import(function (out)
  SlipeClientGui = Slipe.Client.Gui
  SystemNumerics = System.Numerics
  WpfRendererCegui = WpfRenderer.Cegui
end)
System.namespace("WpfRenderer.Cegui.Elements", function (namespace)
  namespace.class("WpfGuiTabPanel", function (namespace)
    local __ctor__
    __ctor__ = function (this, tabControl, parent)
      SlipeClientGui.TabPanel.__ctor__[2](this, SystemNumerics.Vector2(System.ToSingle(tabControl:getMargin():getLeft()), System.ToSingle(tabControl:getMargin():getTop())), SystemNumerics.Vector2(System.ToSingle(tabControl:getWidth()), System.ToSingle(tabControl:getHeight())), false, parent)
      WpfRendererCegui.GuiWpfHelper.AttachHandlers(this, tabControl)

      WpfRendererCegui.GuiWpfHelper.CreateChildren(this, tabControl)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Gui.TabPanel
        }
      end,
      __ctor__ = __ctor__
    }
  end)
end)
