-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientGui
local SystemNumerics
local WpfRendererCegui
System.import(function (out)
  SlipeClientGui = Slipe.Client.Gui
  SystemNumerics = System.Numerics
  WpfRendererCegui = WpfRenderer.Cegui
end)
System.namespace("WpfRenderer.Cegui.Elements", function (namespace)
  namespace.class("WpfGuiList", function (namespace)
    local __ctor__
    __ctor__ = function (this, listBox, parent)
      SlipeClientGui.GridList.__ctor__[2](this, SystemNumerics.Vector2(System.ToSingle(listBox:getMargin():getLeft()), System.ToSingle(listBox:getMargin():getTop())), SystemNumerics.Vector2(System.ToSingle(listBox:getWidth()), System.ToSingle(listBox:getHeight())), false, parent)
      this:AddColumn("", 1)
      WpfRendererCegui.GuiWpfHelper.AttachHandlers(this, listBox)

      WpfRendererCegui.GuiWpfHelper.CreateChildren(this, listBox)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Gui.GridList
        }
      end,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x206, nil, System.Windows.Controls.ListBox, out.Slipe.Client.Gui.GuiElement }
          },
          class = { 0x4 }
        }
      end
    }
  end)
end)
