-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientGui
local SlipeMtaDefinitions
System.import(function (out)
  SlipeClientGui = Slipe.Client.Gui
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("WpfRenderer.Cegui.Elements", function (namespace)
  namespace.class("WpfGuiListItem", function (namespace)
    local __ctor__
    __ctor__ = function (this, item, parent)
      local list = System.cast(SlipeClientGui.GridList, parent)
      local row = SlipeMtaDefinitions.MtaClient.GuiGridListAddRow(list:getMTAElement(), System.cast(System.String, item:getContent()), "")
    end
    return {
      __ctor__ = __ctor__
    }
  end)
end)
