-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientGui
local SystemNumerics
local WpfRendererCegui
System.import(function (out)
  SlipeClientGui = Slipe.Client.Gui
  SystemNumerics = System.Numerics
  WpfRendererCegui = WpfRenderer.Cegui
end)
System.namespace("WpfRenderer.Cegui.Elements", function (namespace)
  namespace.class("WpfGuiButton", function (namespace)
    local __ctor__
    __ctor__ = function (this, button, parent)
      SlipeClientGui.Button.__ctor__[2](this, SystemNumerics.Vector2(System.ToSingle(button:getMargin():getLeft()), System.ToSingle(button:getMargin():getTop())), SystemNumerics.Vector2(System.ToSingle(button:getWidth()), System.ToSingle(button:getHeight())), System.cast(System.String, button:getContent()), false, parent)
      WpfRendererCegui.GuiWpfHelper.AttachHandlers(this, button)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Gui.Button
        }
      end,
      __ctor__ = __ctor__
    }
  end)
end)
