-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientGui
System.import(function (out)
  SlipeClientGui = Slipe.Client.Gui
end)
System.namespace("WpfRenderer.Cegui.Elements", function (namespace)
  namespace.class("WpfGuiComboBoxItem", function (namespace)
    local __ctor__
    __ctor__ = function (this, box, parent)
      SlipeClientGui.ComboBoxItem.__ctor__(this, System.cast(System.String, box:getContent()), System.cast(SlipeClientGui.ComboBox, parent))
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Gui.ComboBoxItem
        }
      end,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x206, nil, System.Windows.Controls.ComboBoxItem, out.Slipe.Client.Gui.GuiElement }
          },
          class = { 0x4 }
        }
      end
    }
  end)
end)
