-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Client.IO", function (namespace)
  -- <summary>
  -- Class representing the cursor of the local player
  -- </summary>
  namespace.class("Cursor", function (namespace)
    local getType, getVisible, SetVisible
    getType = function ()
      return SlipeMtaDefinitions.MtaClient.GuiGetCursorType()
    end
    getVisible = function ()
      return SlipeMtaDefinitions.MtaClient.IsCursorShowing()
    end
    -- <summary>
    -- Set the visibility and whether or not controls should be disabled
    -- </summary>
    SetVisible = function (visible, toggleControls)
      return SlipeMtaDefinitions.MtaClient.ShowCursor(visible, toggleControls)
    end
    return {
      getType = getType,
      getVisible = getVisible,
      SetVisible = SetVisible
    }
  end)
end)
