-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeSharedIO
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedIO = Slipe.Shared.IO
end)
System.namespace("Slipe.Client.IO", function (namespace)
  namespace.class("MtaDebug", function (namespace)
    local getActive
    getActive = function (this)
      return SlipeMtaDefinitions.MtaClient.IsDebugViewActive()
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.IO.SharedMtaDebug
        }
      end,
      getActive = getActive
    }
  end)
end)
