-- Generated by CSharp.lua Compiler
local System = System
local WpfRendererCeguiElements
System.import(function (out)
  WpfRendererCeguiElements = WpfRenderer.Cegui.Elements
end)
System.namespace("WpfRenderer.Cegui", function (namespace)
  namespace.class("CeguiWpfRenderer", function (namespace)
    local Render
    Render = function (window)
      local guiWindow = WpfRendererCeguiElements.WpfGuiWindow(window)

      return guiWindow
    end
    return {
      Render = Render
    }
  end)
end)
