-- Generated by CSharp.lua Compiler
return function (out)
  do
    out = (out and #out > 0) and (out .. '.') or ""
    local require = require
    local load = function(module) return require(out .. module) end

    -- load all files
    load("Source.WpfCoreTest.obj.Debug.netcoreapp3_0.App_g")
    load("Source.WpfCoreTest.obj.Debug.netcoreapp3_0.MainWindow_g")
  end

  System.init({
    "WpfCoreTest.App",
    "WpfCoreTest.MainWindow"
  }, {
    Main = "WpfCoreTest.App.Main"
  })
end
