-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedIO
System.import(function (out)
  SlipeSharedIO = Slipe.Shared.IO
end)
System.namespace("Slipe.Server.IO", function (namespace)
  namespace.class("MtaDebug", function (namespace)
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.IO.SharedMtaDebug
        }
      end
    }
  end)
end)
