-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedElements
System.import(function (out)
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Client.Elements", function (namespace)
  namespace.class("ResourceRootElement", function (namespace)
    local __ctor__
    __ctor__ = function (this, element)
      SlipeSharedElements.Element.__ctor__[2](this, element)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Elements.Element
        }
      end,
      __ctor__ = __ctor__
    }
  end)
end)
